# Generated by scripts/generate-contracts.mjs. Do not edit.
# Authority: packages/contracts/catalogs/v1/import-fields.json
IMPORT_FIELD_CATALOG_VERSION = "1.2.0"
IMPORT_FIELD_ALIAS_RULES: tuple[tuple[str, tuple[str, ...]], ...] = (
    ("orderNumber", ("备货单号", "备货单", "order number",)),
    ("containerNumber", ("集装箱号", "箱号", "柜号", "container number",)),
    ("productNumber", ("货号.产品货号", "产品货号", "货号", "sku",)),
    ("shippedQuantity", ("出运数量", "发运数量", "shipped quantity",)),
    ("quantityUnit", ("出运数量单位", "数量单位", "单位", "quantity unit",)),
    ("contractNumber", ("合同号", "合同编号", "contract number",)),
    ("customsClearanceStatus", ("清关状态", "清关完成状态", "customs clearance status",)),
    ("customsClearanceActualAt", ("实际清关日期", "实际清关完成时间", "customs cleared at",)),
    ("unloadCompletionStatus", ("卸柜状态", "卸柜完成状态", "unload status",)),
    ("unloadCompletedActualAt", ("实际卸柜时间", "实际卸柜完成时间", "unload completed at",)),
    ("emptyConfirmationStatus", ("空箱状态", "卸空状态", "空箱确认状态", "empty confirmation status",)),
    ("emptyConfirmedActualAt", ("实际卸空时间", "实际空箱确认时间", "empty confirmed at",)),
    ("emptyEstimatedAt", ("卸空日期", "预计卸空时间", "推导空箱时间", "empty estimated at",)),
    ("timeSourceSystem", ("时间来源系统", "来源系统", "time source system",)),
    ("timeSourceUtcOffset", ("时间来源UTC偏移", "来源UTC偏移", "UTC偏移", "time source utc offset",)),
    ("timeEvidenceRef", ("时间证据ID", "证据ID", "time evidence id",)),
    ("timeDerivationRuleVersion", ("时间推导规则版本", "推导规则版本", "time derivation rule version",)),
)
