// Generated by scripts/generate-contracts.mjs. Do not edit.
// Authority: packages/contracts/catalogs/v1/canonical-events.json
export type CatalogEventCode =
  | "cargo_ready"
  | "empty_picked_up"
  | "stuffed"
  | "loaded"
  | "departed"
  | "sailing"
  | "gate_in"
  | "transit_arrived"
  | "transit_departed"
  | "arrived"
  | "berthed"
  | "discharged"
  | "available"
  | "release"
  | "hold"
  | "hold_released"
  | "customs_filed"
  | "inspection"
  | "container_customs_completed"
  | "rail_handover"
  | "gate_out"
  | "delivered"
  | "warehouse_arrival"
  | "unloaded"
  | "unstuffed"
  | "returned_empty"
  | "dumped"
  | "rolled"
  | "cancelled"
  | "changed"
  | "delay"
  | "overdue";
export type CatalogEventOwnerDomain =
  | "booking-origin"
  | "ocean-port-visibility"
  | "customs-compliance"
  | "inland-fulfillment"
  | "shipment-registry"
  | "charges-settlement";
export type CatalogEventRole =
  "milestone" | "evidence" | "prerequisite" | "exception";
export type CatalogTimeKind = "planned" | "estimated" | "actual";
export interface CanonicalEventCatalogItem {
  eventCode: CatalogEventCode;
  eventVersion: 1;
  nameCn: string;
  definition: string;
  role: CatalogEventRole;
  ownerDomain: CatalogEventOwnerDomain;
  defaultNodeCode: string | null;
  allowedTimeKinds: CatalogTimeKind[];
  completionEligibleNodeCodes: string[];
  provenance: string[];
}
declare const catalog: CanonicalEventCatalogItem[];
export default catalog;
