// Generated by scripts/generate-contracts.mjs. Do not edit.
// Authority: packages/contracts/catalogs/v1/import-fields.json
export type ImportFieldCode =
  | "orderNumber"
  | "containerNumber"
  | "productNumber"
  | "shippedQuantity"
  | "quantityUnit"
  | "contractNumber"
  | "customsClearanceStatus"
  | "customsClearanceActualAt"
  | "unloadCompletionStatus"
  | "unloadCompletedActualAt"
  | "emptyConfirmationStatus"
  | "emptyConfirmedActualAt"
  | "emptyEstimatedAt"
  | "timeSourceSystem"
  | "timeSourceUtcOffset"
  | "timeEvidenceRef"
  | "timeDerivationRuleVersion";
export type ImportFieldScope = "header" | "line";
export type QuantityUnitCode = "piece" | "carton" | "set" | "pallet";
export type ImportTimeFactCode =
  | "customs_clearance_completed"
  | "container_unloading_completed"
  | "container_empty_confirmed"
  | "container_empty_estimated";
export type ImportTimeKind = "actual" | "estimated";
export type ImportTimeCaptureSource = "controlled_import" | "system_derived";
export interface ImportFieldDefinition {
  code: ImportFieldCode;
  label: string;
  scope: ImportFieldScope;
  required: boolean;
  aliases: string[];
}
export interface QuantityUnitDefinition {
  code: QuantityUnitCode;
  label: string;
  aliases: string[];
}
export interface ImportTimeFactDefinition {
  code: ImportTimeFactCode;
  label: string;
  timeFieldCode: ImportFieldCode;
  statusFieldCode?: ImportFieldCode;
  completedStatusAliases: string[];
  timeKind: ImportTimeKind;
  captureSource: ImportTimeCaptureSource;
  eventCode: string | null;
  requiresEvidence: boolean;
  requiresDerivationRule: boolean;
}
export interface ImportFieldCatalog {
  version: string;
  fields: ImportFieldDefinition[];
  quantityUnits: QuantityUnitDefinition[];
  timeFacts: ImportTimeFactDefinition[];
}
declare const catalog: ImportFieldCatalog;
export default catalog;
