// Generated by scripts/generate-contracts.mjs. Do not edit.
// Authority: packages/contracts/catalogs/v1/lifecycle-nodes.json
import type { CompletionMode, LifecycleNodeCode } from ".";
export type CatalogNodeApplicability = "required" | "optional";
export interface LifecycleNodeCatalogItem {
  sequence: number;
  nodeCode: LifecycleNodeCode;
  applicability: CatalogNodeApplicability;
  completionMode: CompletionMode;
}
declare const catalog: LifecycleNodeCatalogItem[];
export default catalog;
